# 如果想为此模版做出贡献，请先参考以下官方文档 (如需更新链接，请直接替换原短链接，在提交 PR 时请Ping @01101sam)
# https://link.0s.hk/gh-docs-9eb797
name: 🪪 vCard 更新请求
description: 请求更新已有的 vCard
title: '[vCard 更新请求]: '
labels: [ "vcard", "enhancement", "Pending" ]

body:
  # User's README and agreement
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意为项目做出贡献！
        ## 以下是一些注意事项，可以让更新 vCard 更加顺利
        
        ### ❗ | 确定没有相同的 vCard 已被提出. 如有, 请到该 ISSUE 下方留言需要更新的内容.
        ### ❗ | 确定这是已有 vCard 的更新请求. 如果是新的 vCard，请使用 [vCard 新增请求](https://github.com/metowolf/vCards/issues/new?template=01-new-vcard.yaml)
        ### ✍️ | 请准确填写所有信息
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述注意事项，并确认我已经准备好了所有必要的信息。"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/metowolf/vCards/issues) 中找过我准备更新的 vCard，没有找到相同的 ISSUE。"
          required: true
        - label: 我已知晓并同意，此处仅用于更新 vCard。若这个 Issue 是关于其他问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
          required: true

  # User's data
  - type: markdown
    attributes:
      value: |
        ## 联系人信息
        请填写您想要更新的 vCard 信息

  - type: input
    id: vcard-existing
    attributes:
      label: 现有 vCard
      placeholder: 请输入现有的 vCard 名称 (可以在 /data 目录下找到)
    validations:
      required: true

  - type: dropdown
    id: vcard-group
    attributes:
      label: 联系人分类
      description: 如果无需更改分类，请选择「None」
      options:
        - 互联网
        - 出行购票
        - 外卖订餐
        - 应用软件
        - 影音娱乐
        - 快递物流
        - 房产中介
        - 政府机构
        - 本地生活
        - 汽车行业
        - 电商购物
        - 租车代驾
        - 证券保险
        - 通讯服务
        - 金融银行
        - 其它
        - 新增分类（请在下方说明）

  - type: input
    id: vcard-group-new
    attributes:
      label: 新增分类
      description: 如果您选择了「新增分类」，请在此处填写您的分类名称
      placeholder: 请输入新增分类名称

  - type: textarea
    id: vcard-thumbnail
    attributes:
      label: 缩略图
      description: 您可以填写图片链接或直接上传到这里, 如不为空将会覆盖原有图片

  - type: input
    id: vcard-name
    attributes:
      label: 显示名称
      description: 请填写联系人的显示名称, 如不为空将会覆盖原有信息
      placeholder: 如 "中国移动", "麦当劳"

  - type: input
    id: vcard-name-en
    attributes:
      label: 显示名称 (英文)
      description: 请填写联系人的显示名称
      placeholder: 如 "China Mobile", "McDonald's China"

  - type: input
    id: vcard-org
    attributes:
      label: 组织名称
      description: 请填写联系人所在的组织名称, 如不为空将会覆盖原有信息
      placeholder: 组织名称, 公司名称等

  - type: markdown
    attributes:
      placeholder: |
        ## 联系人信息
        此处采用 diff 格式，格式如下:
        
        a<空格>内容: 添加内容
        d<空格>内容: 删除内容
        
        注意: 请确保您的 diff 格式正确(空格为半型符号)，否则可能会导致无法识别

  - type: textarea
    id: vcard-tel
    attributes:
      label: 电话号码
      placeholder: |
        如何更新电话号码:
        - a 11198765432
        - d 11198765433

        其中:
        - a: 添加
        - d: 删除
      render: markdown

  - type: textarea
    id: vcard-website
    attributes:
      label: 官方网站
      description: 请填写联系人的官方网址 (不用填写 http/https)
      placeholder: |
        如何更新网站:
        - a example.com
        - d example.org

        其中:
        - a: 添加
        - d: 删除
      render: markdown

  - type: textarea
    id: vcard-email
    attributes:
      label: 电子邮箱
      placeholder: |
        如何更新邮箱:
        - a me@example.com
        - d alex@example.com
        
        其中:
        - a: 添加
        - d: 删除
      render: markdown

  - type: textarea
    id: vcard-note
    attributes:
      label: 备注
      description: 联系人的备注信息
      placeholder: "警告: 将会覆盖原有备注信息"
      render: markdown
