# 如果想为此模版做出贡献，请先参考以下官方文档 (如需更新链接，请直接替换原短链接，在提交 PR 时请Ping @01101sam)
# https://link.0s.hk/gh-docs-9eb797
name: ✨ 新功能提议或改进
description: 为 vCard / 自建 CardDAV 提议新功能或改进
title: '[提议]: '
labels: [ "enhancement", "Pending" ]

body:
  # User's README and agreement
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意为 vCard / 自建 CardDAV 提出新功能或改进！
        ## 以下是一些注意事项，请务必阅读让我们能够更容易处理
        
        ### ❗ | 确定没有相同问题的ISSUE已被提出. 如有, 请到该 ISSUE 下方留言需要更新的内容.
        
        ## 如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》
        链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述注意事项，并确认我已经准备好了所有必要的信息。"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/metowolf/vCards/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。"
          required: true
        - label: 我已知晓并同意，此处仅用于提议新功能或改进。若这个 Issue 是关于其他问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      options:
        - vCard
        - CardDAV
        - 其他 (请在下方描述)
    validations:
      required: true

  - type: input
    id: feature-type-other
    attributes:
      label: 其他功能类型
      placeholder: 请在此处描述

  - type: textarea
    id: feature-description
    attributes:
      label: 需要添加的功能内容
      placeholder: 请在这里详细描述新功能的实现方法, 尽可能详细
    validations:
      required: true
